### ISSUE TITLE
Build fails on both server and db images

### ISSUE THREAD

**Issue by Drefsab** [notsureifkevin/ffxi-darkstar-docker#4]
The stable branch of the database now requries mysql 5.6 unless you change the insert statements in the SQL files.

Also the server use gcc7 instead of 5 now. So I edited the server docker file to be:

  apt-get install -y g++-7 && \
  update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90 && \
  apt-get install -y libx32gcc-7-dev && \

Instead of 

  apt-get install -y g++-5 && \
  cd /usr/bin && \
  rm gcc g++ cpp && \
  ln -s gcc-5 gcc && \
  ln -s g++-5 g++ && \
  ln -s cpp-5 cpp && \

This resolved the issues for me and now the comtainers both build and start up :)

**Comment by kvncrw** [comment]
Thank you, feel free to make a PR and I'll test/merge, otherwise, I'll make the changes in the next week or two. I appreciate you posting the fix either way :) I mostly play FFXIV when I have time these days.

**Comment by Drefsab** [comment]
Submitted the PR, just thought id share as a had about of nostalga for the game and wanted to get it running love docker so this was my goto option. Hopefully it will help some people. Just need a private server for FFXIV now :D
